info:
  contact: {}
paths:
  /announcements/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a single announcement from the database
      parameters:
      - description: Announcement ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get an announcement by ID
      tags:
      - Announcements
swagger: "2.0"
